<?php

namespace Kiri\Message\Handler\TreeHelper;

use Kiri\Message\Handler\Handler;

class MethodOptions extends HashTree implements TreeLeafInterface
{


	/**
	 * @param string $path
	 * @return Handler|null
	 */
	public function searchLeaf(string $path): ?static
	{
		$data = parent::searchLeaf($path); // TODO: Change the autogenerated stub
		if ($data == null) {
			return parent::searchLeaf("/*");
		}
		return $data;
	}

}
